name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: yezz123/setup-uv@v4

      - name: Pin python-version ${{ matrix.python-version }}
        run: uv python pin ${{ matrix.python-version }}

      - name: Setup python ${{ matrix.python-version }} and uv
        shell: bash
        run: |
          uv sync --frozen

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test

      - name: Run check
        run: make check
